### ISSUE TITLE
use case diagram

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#52] opened 2023-04-04 12:17 UTC
creating use case diagram

**Comment by bakikucukcakiroglu** [comment] 2023-04-08 21:11
Explanation: This issue is assigned to a sub-group. Since all steps of the issue is related, it can not be separated into small chunks. All other individual efforts will be reported additionally.

Tasks to be done:

- Create a shared Figma file

- Define Use Cases according to features of the platform and the fundamental needs of the user

- Define a common structure to draw diagram.

- Draw sequence diagrams.

**Comment by bakikucukcakiroglu** [comment] 2023-04-08 21:32
All the work for creating this diagram is evenly shared between sub-group members. Group members cannot state their individual work since we worked simultaneously in a shared Figma file.

The work can be seen by the following image, link to the actual source file will be shared later as a measurement against a violation of intellectual property rights.

<img width="622" alt="Screen Shot 2023-04-09 at 00 26 44" src="https://user-images.githubusercontent.com/61244299/230743153-c16b3517-77b5-4549-95ea-7bb1d60f0bfe.png">

**Closed by bakikucukcakiroglu** 2023-04-08 21:32 UTC
Labels: status: in review, priority: high, effort: high, type: new feature
