### ISSUE TITLE
Wiki Home Page Main Issue

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#13] opened 2023-03-07 08:42 UTC
Update home page with details about our project.

**Comment by bahadirgezer** [comment] 2023-03-07 08:44
Updated the wiki home page and added a "what is our project about?" section. Commit [link](https://github.com/bounswe/bounswe2023group8/wiki/Home/3b2952c71ea2427dd96a67dece60e64dec28c373).

**Comment by EgemenKaplan** [comment] 2023-03-07 09:23
I think this might be a duplicate of the issue I created earlier. We cannot delete issues I think so I will label this one as duplicate

**Comment by EgemenKaplan** [comment] 2023-03-08 08:00
I realized that I misunderstood the difference. You are talking about wiki home page, which is different than Readme.md. My bad.

**Closed** 2023-03-13 16:17 UTC
Labels: type: wiki, type: improvement, status: backlog, priority: low, effort: low
