### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by begumyivli** [bounswe/bounswe2023group8#56] opened 2023-04-07 16:17 UTC
Creating Sequence diagram based on class diagram and use case diagram

**Comment by bakikucukcakiroglu** [comment] 2023-04-08 21:08
Explanation: This issue is assigned to a sub-group. Since all steps of the issue is related, it can not be separated into small chunks. All other individual efforts will be reported additionally.

Tasks to be done:

- Create a shared Figma file

- Define sequences to be created based on Class Diagram and Use Case Diagram. 

- Define a common structure to draw sequences.

- Draw sequence diagrams.

**Comment by bakikucukcakiroglu** [comment] 2023-04-08 21:18
Note: Awating class diagrams revision before improving sequence diagrams.

**Comment by bakikucukcakiroglu** [comment] 2023-04-09 08:46
I've started and completed "View Post", "View IA" and "View Profile" sequences for registered user.

The work can be seen by the following image: 

<img width="788" alt="Screen Shot 2023-04-09 at 11 45 36" src="https://user-images.githubusercontent.com/61244299/230763207-c6722288-da6c-4c96-933f-a02791e61258.png">

**Comment by ozturkMirac** [comment] 2023-04-09 11:03
I've started and completed "Modify IA", "Modify Post" and "Modify User" sequences for registered user.

The work can be seen by the following image:

![Screenshot (27)](https://user-images.githubusercontent.com/123721259/230768767-a982e780-a0d6-44be-bd23-3cd85228e2d7.png)

**Comment by sudek0** [comment] 2023-04-09 11:06
I've started and completed "Register" sequence.

The work can be seen by the following image:
![Adsız](https://user-images.githubusercontent.com/110811440/230768893-fe764bd0-4c88-4b2a-8d95-f2588440c2f0.png)

**Comment by begumyivli** [comment] 2023-04-09 11:39
I've started and completed "Login" and "Logout" sequence.

The work can be seen by the following image:
<img width="958" alt="Ekran Resmi 2023-04-09 14 38 45" src="https://user-images.githubusercontent.com/88006241/230770377-fd0d1b43-a5f3-48c3-a462-f07db220fda6.png">

**Comment by enesYildiz69** [comment] 2023-04-09 13:01
I've started and completed "Report" and "Ban" sequences.

The work can be seen by the following images:

![230771410-d102e182-ea35-428b-ab17-2d6820040695](https://user-images.githubusercontent.com/61426414/230774048-cc9647b0-080b-4943-8f14-17eaa6a18c7b.png)
![230771413-39bc2226-f838-4ffe-8004-2f35258d2816](https://user-images.githubusercontent.com/61426414/230774054-2d0bd99e-c77c-4c1c-b6dc-857c508fd007.png)

**Comment by EgemenKaplan** [comment] 2023-04-09 17:08
I am removing myself since I switched to class diagram revision during the meeting, during which the initial form of sequence diagrams was incepted.

**Comment by FurkanOzcelik** [comment] 2023-04-09 18:39
I've worked on Create IA and View pages. I've created some of view pages and took role on deciding on general structure of view pages.
<img width="314" alt="Screenshot_1" src="https://user-images.githubusercontent.com/45850661/230790643-c083115e-f559-4077-adb3-092dc806017f.png">
<img width="508" alt="Screenshot_2" src="https://user-images.githubusercontent.com/45850661/230790645-0e0df0bc-32c2-4d1e-93f5-5efbf85bb15e.png">

**Closed by FurkanOzcelik** 2023-04-09 18:39 UTC
Labels: status: to-do, status: in progress, priority: high, effort: high, type: new feature
